### ISSUE TITLE
fix_on, fix_off, kwargs in RFE method

### ISSUE THREAD

**Issue by DS-Wen** [prisms-center/CASMcode#103]
Dear Developers,

I was trying to fit the cluster expansions with RFE method but couldn't use the "fix_on" and "fix_off" keyword arguments in the setup json file. We can easily do that with GenericAlgorithms or PopulationBestFirst. Is there a way to fix on and off the desired clusters in the RFE method? 

Thank you,
DS

**Comment by bpuchala** [comment]
No, currently "fix_on" and "fix_off" are only available for the evolutionary algorithms we implemented ourselves, not the sciki-learn algorithms.

There could be a couple ways to implement this feature: 

(i) Recognize a "feature_selection"/"constraints_kwargs" option, which enables the following: run feature selection with standard algorithms, but only passing correlations not "fixed off", then enforce the features "fixed on" (and potentially "n_features_min" and "n_features_max" via a RFE-like algorithm) and re-estimate ECI. This would entail modifying the function casm.learn.feature_selection.fit_and_select.

(ii) Implement a class (i.e. RFEWithConstraints) in 'casm.learn.feature_selection' that accepts a constaints_kwargs constructor kwarg in addition to their normal kwargs, and re-implement the algorithm so that the constraints are enforced at each step in the algorithm. This is how the evolutionary algorithms are currently implemented.
