### ISSUE TITLE
how to change the  the submitting code from pbs to lsf

### ISSUE THREAD

**Issue by deRheart** [prisms-center/CASMcode#116]
My computer use the lsf to submit the job，but CASM use the pbs.   And it seems that pbs  just suppot the "pbs" and "slurm"  to manage the jobs. So i want to know how to change the submitting code ?

**Comment by bpuchala** [comment]
The most recent versions of CASM are now using the [prisms_jobs](https://prisms-center.github.io/prisms_jobs_docs/index.html) Python package instead of 'pbs'. To add support for a new job management software you have to implement a new "interface", following the example for [torque](https://github.com/prisms-center/prisms_jobs/blob/master/prisms_jobs/interface/torque.py) or [slurm](https://github.com/prisms-center/prisms_jobs/blob/master/prisms_jobs/interface/slurm.py). 

A new interface needs to define the 'NAME' variable and implement the functions listed under the "### Required ###" line in those files.

The interface can be implemented inside ```prisms_jobs/interface``` as a standard like torque and slurm, or as an external Python module by specifying it via the "software" parameter in the ```PRISMS_JOBS_DIR/config.json``` file.  See [here](https://prisms-center.github.io/prisms_jobs_docs/config.html) for info.

If you do implement it, it would be great to get a pull request incorporating it into prisms_jobs.

**Comment by Anshuman5** [comment]
Where can I find the most recent version of CASM which uses 'prisms_jobs' python package instead of 'pbs'?
