### ISSUE TITLE
selecting individual (or small set) of configurations

### ISSUE THREAD

**Issue by jjcordell** [prisms-center/CASMcode#123]
First, thanks to the developers; the CASM code looks like it can be very useful in my research.

Context:
I have run through the ZrO example system up to the monte carlo simulation and everything seems to be working well. I am now working with a ternary system with a primitive cell of 16 atoms. When I enumerate configurations, there are a lot. Even with some filters, I end up with >1000 configs per 32 atom supercell (>10 million for 64 atom supercells). 

I would like to select individual or small sets of configs from a given supercell to calculate energies with VASP, but am having difficulty just making a selection. I have tried 
`casm select --set "eq(configname, SCEL2_2_1_1_0_1_1/1)"`
and a dozen or more variations on syntax but always get an error similar to this:
`ERROR: Failure to select using criteria "eq(configname, 'SCEL2_2_1_1_0_1_1/1')" for configuration SCEL1_1_1_1_0_0_0/0
    Reason:  stod`
I have read through the slides of the presentations for the demo and searched any relevant help documentation for the `select` command (properties and operators) but nothing I found actually led to a selection.
The command
`casm select --set "eq(comp(a), 0.5)"`
works, but in my case is the same as selecting all configurations.

Problem:
I would like to select configurations by name; what is the syntax to do this?

Thanks again!

**Comment by jcthomas** [comment]
Due to some current limitations in the type system in the casm query syntax, the 'eq' operator can only be used for numerical comparisons. String comparisons can be performed using regular expressions using the 're' operator (which returns true if the regular expression matches the entire string being compared) and the 'rs' operator (which returns true if the regular expression matches a substring of the string being compared. Thus, the selection you gave as an example can be performed using
`casm select --set "re(configname, 'SCEL2_2_1_1_0_1_1/1')"`
or you can select configurations 0 through 9 in the same supercell :
`casm select --set "re(configname, 'SCEL2_2_1_1_0_1_1/[0-9]')"`

The 're' and 'rs' operators are powered by boost.regex, and so use roughly the Perl regular expressions syntax. More info is available here: https://www.boost.org/doc/libs/1_68_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html

**Comment by bpuchala** [comment]
Glad CASM is useful for you.  The ```eq``` query operator only works for comparing numbers right now.  For comparing strings you have to use ```re``` or ```rs```.

**Comment by jcthomas** [comment]
You can of course also construct your own selection file using a text editor. casm commands that operate on selections or take a selection as input can accept a selection file via the `--configs` modifier

**Comment by jjcordell** [comment]
Thanks for the super quick responses. `casm select --set "re(configname, 'SCEL2_2_1_1_0_1_1/[0-9]')"` is exactly what I'm looking for.
