### ISSUE TITLE
command "casm-calc --setup" gives error

### ISSUE THREAD

**Issue by jungsdao** [prisms-center/CASMcode#141]
**Dear developer
I just started casm code and trying this step by step, but I encountered a problem.
After pasting "INCAR", "KPOINTS", "POSCAR", relax.json, SPECIES into "~/training_data/settings/calctype.VASP", I wrote "casm-calc --setup" to distribute above files to each configuration directories. 
However, an error popped up as follow.**

/TGM/Apps/CASM/0.2.1/lib/python2.7/site-packages/pbs.py:68: DeprecationWarning: 
    
Sh.py is the new pbs.  Please download and install sh.py with the following
command:

    $ pip install sh
    
or

    $ easy_install sh

Sh.py includes many enhancements and will be the supported subprocess launcher
for the future.  See its documentation here http://amoffat.github.com/sh/.

To migrate existing code, try this:

    import sh as pbs

  """, DeprecationWarning)
list index out of range

**How can I circumvent this problem??
Recently pbs job manager was updated to SLURM manager in our cluster system and I'm suspecting this as the source of problem, but not quite sure.**

**Comment by bpuchala** [comment]
I think there is a name collision between a package on your system called "pbs", and the "pbs" package that version 0.2 of CASM uses to submit jobs (https://github.com/prisms-center/pbs). 

I think perhaps you installed the original, instead of the latter, because our pbs is not on pip. See it's documentation for installation instructions.

The newer version of CASM is 0.3.X, which uses the "prisms_jobs" package, an updated version of the original "pbs". "prisms_jobs" is on pip and is installed automatically if you install CASM as a conda package, as shown [here](https://prisms-center.github.io/CASMcode_docs/pages/installation.html).
