### ISSUE TITLE
Restricting compositional space

### ISSUE THREAD

**Issue by DKasdorf** [prisms-center/CASMcode#150]
Hi Casm Developers,

first of all: thank you for your powerful software!

I've got a problem with setting up my prim.json-file correctly. My primitive structure needs to be of higher symmetry in order to construct structures of two subgroups of it. Additionally, i want to be able to add a single structure in which the octahedral sites (not occupied in any other case) are occupied.
The resulting composition axes are correct for my definition of the prim.json but the compositional space is far too big (mainly because of the octahedral sites) for my purpose. 
Is it possible to restrict the compositional space at this point? When yes, then how?
The only workaround i can imagine is to only precisely enumerate configurations i need and then set the reference manually.
A more general form of the question above would be: How can i effectively incorporate multiple symmetries in my cluster expansion?
Thanks in advance!

**Comment by jcthomas** [comment]
If you plan to consider only a single structure involving the octahedral sites, it likely is not necessary to treat it as an actual configuration within your project. You can instead set one of your reference states to be the octahedral-site structure, and then any configuration within your project having positive formation energy will be energetically unstable relative to some phase mixture of your reference states (including the octahedral-site structure, depending on the composition).

As I understand it, you have two types of structures (A-site-occupied [i.e., octahedral] and B-site-occupied). If A-site and B-site structure types are totally distinct and it is not possible for A and B sites to mix (e.g., due to energetic penalties), then you can consider the two structure types separately, within two separate CASM projects. Once you have data for both projects (making sure to manually set both projects to have the same reference compounds), you can visualize the convex hulls using Matlab or matplotlib to determine thermodynamic stability over the entire composition range.

If, in addition to A-type and B-type structures, you also have mixed A/B-type, then it may be necessary to consider both types of sites within the same CASM project. As you suggest, the best way to treat a system with constrained composition at present is to the restrict enumeration of the training data. To do this, you can apply a filter to any `casm enum` command. For example,
````
casm enum -m ConfigEnumAllOccupations --max 4 --filter "le(atom_frac(H),0.5)"
````
will enumerate all configurations up to volume-4 supercells and having an atom fraction of hydrogen (H) less than or equal to 0.5.

If you have already constructed a basis set you can additionally filter your enumeration by putting limits on correlation values. In this way, you can constrain sublattice compositions or pair correlations.  

If you find that enumeration is taking too long for large supercells (because of the large number of sites), you can use the `ConfigEnumRandomOccupations` method, and tune the `n_config` argument to suit your needs.

**Comment by DKasdorf** [comment]
Thank you very much for the fast and extensive answer!

Is it also possible to restrict the enumeration by creating a custom composition axis?

I would also like to request something in this context: A property tag for site-specific atom fractions (sites defined by prim.json). This would come in handy for some querying and/or enumeration.

**Comment by jcthomas** [comment]
You can specify a custom set of composition axes, although there is no way currently to specify it from the command line. I have provided instructions below for editing the appropriate settings file. Once you do so, you will be able to refer to these custom compositions via `comp(a)`, `comp(b)`, etc., to filter your enumeration.

Your suggestion for a sublattice composition property is a good one. We will be adding a number of query-able properties in the next version of CASM and will try to implement this as well.


**Specifying custom composition axes**
The composition axes are defined in the file `$PROJECT_HOME/training_data/settings/calctype.default/ref.default/composition_axes.json`. For a given `prim.json`, all of the possible compositions of the system are contained in a line segment (binary), polygon (ternary), polyhedron (quaternary), etc. By default, CASM finds composition axes by taking one vertex of this shape as the origin and then defining axes from that origin along edges of the shape. However, you may define custom axes in terms of any set of points as long as they are not coincident (binary), colinear (ternary), etc.

The points in `composition_axes.json` are specified in terms of # of atoms per primitive cell. Here is an example entry for a somewhat complicated chemistry involving species "A", "B", and "C", with possibility of vacancies:
````
    "3" : {
      "components" : [ "A", "B", "C", "Va" ],
      "independent_compositions" : 2,
      "origin" : [
        [ 1.000000000000 ],
        [ 0.000000000000 ],
        [ 1.000000000000 ],
        [ 1.000000000000 ]
      ],
      "a" : [
        [ 1.000000000000 ],
        [ 0.000000000000 ],
        [ 2.000000000000 ],
        [ 0.000000000000 ]
      ],
      "b" : [
        [ 1.000000000000 ],
        [ 1.000000000000 ],
        [ 0.000000000000 ],
        [ 1.000000000000 ]
      ],
      "mol_formula" : "A(1)B(b)C(1+a-b)Va(1-a)",
      "param_formula" : "a(0.333333+0.333333B+0.333333C-0.666667Va)b(0.666667+0.666667B-0.333333C-0.333333Va)"
    }
````
`"origin"` is the origin point, and the axes are along the vectors `"a"-"origin"` and `"b"-"origin"`. 
 In the example, species "A" is fixed and not allowed to vary, which is why its corresponding value is 1 in all three points. The remaining species, "B", "C", and "Va", effectively form a ternary system, which is why there are two axes.

If you add an entry to composition_axes.json, be sure to give it a new numerical name. The name of the entry above is "3". You can redefine the points ["origin", "a", ..., etc.] as necessary to obtain the axes you want. After you edit the file, you can check it for correctness by running `casm composition --display`.  Be aware that running `casm composition --calc` will overwrite composition_axes.json. The fields `"mol_formula"` and `"param_formula"` are not required. They will be repopulated the next time you run `casm composition --select`.

**Comment by DKasdorf** [comment]
Thank you again for your answer!

Filtering the enumeration definitely works although there are still some "unwanted" structures (we dont know whether the systems mix).

I've also generated new composition axes, but i need a bit more time to check the influence on the generated structures.

**Comment by shaliu19900911** [comment]
> You can specify a custom set of composition axes, although there is no way currently to specify it from the command line. I have provided instructions below for editing the appropriate settings file. Once you do so, you will be able to refer to these custom compositions via `comp(a)`, `comp(b)`, etc., to filter your enumeration.
> 
> Your suggestion for a sublattice composition property is a good one. We will be adding a number of query-able properties in the next version of CASM and will try to implement this as well.
> 
> **Specifying custom composition axes**
> The composition axes are defined in the file `$PROJECT_HOME/training_data/settings/calctype.default/ref.default/composition_axes.json`. For a given `prim.json`, all of the possible compositions of the system are contained in a line segment (binary), polygon (ternary), polyhedron (quaternary), etc. By default, CASM finds composition axes by taking one vertex of this shape as the origin and then defining axes from that origin along edges of the shape. However, you may define custom axes in terms of any set of points as long as they are not coincident (binary), colinear (ternary), etc.
> 
> The points in `composition_axes.json` are specified in terms of # of atoms per primitive cell. Here is an example entry for a somewhat complicated chemistry involving species "A", "B", and "C", with possibility of vacancies:
> 
> ```
>     "3" : {
>       "components" : [ "A", "B", "C", "Va" ],
>       "independent_compositions" : 2,
>       "origin" : [
>         [ 1.000000000000 ],
>         [ 0.000000000000 ],
>         [ 1.000000000000 ],
>         [ 1.000000000000 ]
>       ],
>       "a" : [
>         [ 1.000000000000 ],
>         [ 0.000000000000 ],
>         [ 2.000000000000 ],
>         [ 0.000000000000 ]
>       ],
>       "b" : [
>         [ 1.000000000000 ],
>         [ 1.000000000000 ],
>         [ 0.000000000000 ],
>         [ 1.000000000000 ]
>       ],
>       "mol_formula" : "A(1)B(b)C(1+a-b)Va(1-a)",
>       "param_formula" : "a(0.333333+0.333333B+0.333333C-0.666667Va)b(0.666667+0.666667B-0.333333C-0.333333Va)"
>     }
> ```
> 
> `"origin"` is the origin point, and the axes are along the vectors `"a"-"origin"` and `"b"-"origin"`.
> In the example, species "A" is fixed and not allowed to vary, which is why its corresponding value is 1 in all three points. The remaining species, "B", "C", and "Va", effectively form a ternary system, which is why there are two axes.
> 
> If you add an entry to composition_axes.json, be sure to give it a new numerical name. The name of the entry above is "3". You can redefine the points ["origin", "a", ..., etc.] as necessary to obtain the axes you want. After you edit the file, you can check it for correctness by running `casm composition --display`. Be aware that running `casm composition --calc` will overwrite composition_axes.json. The fields `"mol_formula"` and `"param_formula"` are not required. They will be repopulated the next time you run `casm composition --select`.

I found even I use a custom composition axis, and use filter enumeration, the MC and LTE still flip occupations determined by prim.json. My cluster expansion is only suitable for a certain range of compositions, and the configurations out of this range contain a large number of vacancy and deform too much. Is there any way to run LTE and MC only in the composition range of interest?

**Comment by bpuchala** [comment]
You can run canonical ensemble at specific compositions, but for grand canonical ensemble calculations you cannot restrict the composition range explicitly, only by controlling the chemical potential. 

We may add a feature to help identify the chemical potentials corresponding to a particular composition or composition range though.

**Comment by shaliu19900911** [comment]
> You can run canonical ensemble at specific compositions, but for grand canonical ensemble calculations you cannot restrict the composition range explicitly, only by controlling the chemical potential.
> 
> We may add a feature to help identify the chemical potentials corresponding to a particular composition or composition range though.

Thanks in advance!
