### ISSUE TITLE
--checkhull error

### ISSUE THREAD

**Issue by shaliu19900911** [prisms-center/CASMcode#152]
Dear developer,

I now have a project with only one site, and it is occupied by A, B, and Va. I use pure A and B as references. The DFT Ef and fitted Ef is as blow. I use query on_hull on_clex_hull to check which configurations are on hull, and some are exactly on hull. But when I use --checkhull command, it says:

**Print:
   - clex_hull_dist(ALL,atom_frac) clex(formation_energy) clex_hull_dist(/home/shaliu/Downloads/CASM_WORK/Al23Cu_primitive/.casm/tmp/ALL_dft_hull,atom_frac) 
to "STDOUT"

Initialization error: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 3)

While executing:  | qhull 
Options selected for Qhull 2015.0.6.r 2015/10/20:
  run-id 1705942019  _pre-merge  _zero-centrum**

I use the fitted CE to run LTE with fixed xi_b and increasing xi_a, but I only get pure A (the configuration with Ef=0) at some xi_b. When xi_b reaches a value, I did't get any ground state phase. Could you please tell me why?

![fffff](https://user-images.githubusercontent.com/46279371/58717204-fb0bd580-83ca-11e9-992b-4291c04dd1df.png)

**Comment by bpuchala** [comment]
Hi Sha, would you be willing to email me an archive of your project (excluding calculations) to check these?

**Comment by shaliu19900911** [comment]
I sent you an compressed project. Thanks Brian!

**Comment by bpuchala** [comment]
Hi Sha,

I identified the issues:

With the --checkhull option there is a default "checkhull" option in the casm learn input file that you need to set to ```"primitive_only":false```.  Look at the ```casm learn --settings-format``` output for more details, but basically the default is to only use primitive configurations to check the convex hull because including both the primitive and a supercell of the same configuration can cause problems. In your project you are not including many of the primitive configurations, so too few configurations remained to fit the DFT hull and this caused the error.

With the LTE results, your fit is predicting other ground states that have not been enumerated in your project. CASM currently exits with an error when this occurs because it means you are not calculating the LTE for the real predicted ground states. To address this you'll want to do some combination of enumerating more configurations (so the predicted ground states is in your project) and/or do more work on the fit.
