### ISSUE TITLE
Issue with generating convex hull : ZrO example

### ISSUE THREAD

**Issue by Anshuman5** [prisms-center/CASMcode#169]
![ZrO_hull](https://user-images.githubusercontent.com/29806599/66091559-2bac7900-e53d-11e9-9206-90c0deabec98.JPG)
Hello developers,

I am trying to reproduce the convex hull for ZrO reported in "Thermodynamics of the Zr-O system from first-principles calculations"(2013). I was able to obtain the hull which looks very similar to the one reported in the paper. The issue here is that to plot the formation energy in units of eV/Zr, I had to divide the formation energy obtained by the tutorial (which gives the formation energy in eV/unit cell) by 2. I am a bit confused on why we need to divide the formation energy by 2. 

Thanks!

**Comment by jcthomas** [comment]
There are two normalization conventions utilized by `casm query`. The first, `formation_energy` and `clex(formation_energy)`, reports the formation energy per unit cell (as defined by `prim.json`). The second, `formation_energy_per_species` and `clex(formation_energy_per_species)`, reports the formation energy per atom (excluding vacancies). 

Both are useful in different contexts, but in the case of ZrO_x, the commonly regarded formula unit (comprising a single Zr atom, and a fractional O atom) does not correspond to either extreme. This is because the most compact unit cell of ZrO consists of two formula units (two Zr atoms and two O atoms).

**Comment by Anshuman5** [comment]
Thank you for the reply. 
If I plot formation energy in eV/unit cell to obtain the hull, it looks like the below figure.
Since I am interested in obtaining the formation energy/Zr atom, I divide the formation energy/unit cell by the no. of Zr atoms in the unit cell of the structures lying on the hull. (using the table below). My concern is that the answer obtained in this way does not correspond to the value reported in this paper: "Thermodynamics of the Zr-O system from first-principles calculations"(2013). It would be helpful if you can point the mistake in my method.

![ZrO_hull_2](https://user-images.githubusercontent.com/29806599/66168859-4d683780-e5f3-11e9-9a3d-983a6650e585.JPG)
   
![image](https://user-images.githubusercontent.com/29806599/66169081-0d558480-e5f4-11e9-8c80-90b4977f752a.png)

**Comment by jcthomas** [comment]
The `formation_energy` reported by CASM is already normalized by the number of primitive cells in each configuration. As such, the formation energy that is reported is eV per (2*Zr).

So, in the first row (SCEL3_3_1_1_0_2_2/0), you have a formation energy of **-0.297949 eV/(2*Zr)**. Dividing through by the 2, you'll find that this is equivalent to **-0.1489745 eV/Zr**
