### ISSUE TITLE
Non-intuitive transformations of the primitive cell

### ISSUE THREAD

**Issue by Gustautas** [prisms-center/CASMcode#171]
Hello and thanks for the code,

After running `casm enum -m ScelEnum` I get SCEL file with "funny" transformations for 
supercells:

Supercell Name: 'SCEL1_1_1_1_0_0_0' Number: 0 Volume: 1
Supercell Transformation Matrix: 
 1  1  1
-1  0  0
 0 -1  0
Supercell Name: 'SCEL2_1_1_2_0_0_0' Number: 1 Volume: 2
Supercell Transformation Matrix: 
 1  0 -1
-1  1 -1
 0  0  2
Supercell Name: 'SCEL2_2_1_1_0_0_1' Number: 2 Volume: 2
Supercell Transformation Matrix: 
 1  0  1
-1  0  1
 0 -1 -1
Supercell Name: 'SCEL2_2_1_1_0_1_1' Number: 3 Volume: 2
Supercell Transformation Matrix: 
 1  0  1
 0  1  1
-1 -1  0

Instead of what I would expect to be simply diagonal matrices:

Supercell Name: 'SCEL1_1_1_1_0_0_0' Number: 0 Volume: 1
Supercell Transformation Matrix: 
 1  0  0
 0  1  0
 0  0  1
Supercell Name: 'SCEL2_2_1_1_0_0_0' Number: 1 Volume: 2
Supercell Transformation Matrix: 
 2  0  0
 0  1  0
 0  0  1
and so on...

Any particular reason for such behavior?
Would it be safe to simply define my own "intuitive" transformation matrixes? If yes how to do that?

**Comment by jcthomas** [comment]
Welcome, and thanks for the question. CASM stores supercell lattice vectors in a canonical setting, which is based on two criteria, described below. When you initialize your project, CASM checks whether the provided lattice is in the canonical setting. If not, it will write a new file `prim.niggli.json` in the project directory that is in the canonical setting. If you re-initialize your project by copying `prim.niggli.json` to `prim.json` and re-run `casm init`, it should result in more sensible transformation matrices. 

Unfortunately, CASM uses the canonical lattice vectors for locating data in certain circumstances. I don't think it would be safe to specify custom supercell lattice vectors, as it would very likely lead to unexpected behavior.

For completeness here are the two criteria used to define the canonical setting:

First, the Niggli reduced cell of the lattice vectors is found. This is the most compact definition of the primitive cell (in the sense of smallest surface-area:volume ratio) and also satisfies additional constraints on the lengths of lattice vectors, the angles between them, and the order in which the lattice vectors are listed. For a given lattice, the Niggli cell allows you to find a unique vector [a b c alpha beta gamma] of lattice vectors and the angles between.

The Niggli reduced cell does not uniquely determine the lattice vectors. CASM calculates a unique set of lattice vectors by first finding the point group of the crystal and then calculating all symmetry equivalent sets of lattice vectors, which are rotated copies of the starting lattice vectors (reflections are not considered, as they result in a left-handed coordinate system). CASM then picks a set of lattice vectors that maximizes a set of criteria on the individual elements of the lattice vectors.

**Comment by Gustautas** [comment]
Thanks for the elaborate answer.
So if I understood correctly, it would still be possible to incorporate separately precomputed (using non-reduced primitive cell) configurations into training data, by converting CONTCAR files to Niggli reduced geometry and selecting similar density k-point grid for further DFT calculations using CASM generated configurations?

Or perhaps I am missing something? For example, the converted structures will not be in "CASM standard
orientation", and therefore not usable for further computations?

**Comment by jcthomas** [comment]
You can import previously computed data into a CASM project using the `casm import` command. You can import configurations either with or without associated DFT data. If you choose to import DFT data with the configurations, you will need to generate a `properties.calc.json` file for each structure. These files can be generated using the `vasp.relax.report` python script that is installed with CASM.

There is no need to convert your existing CONTCAR files.  `casm import` will determine the optimal way to transform the lattice vectors (via rigid rotation and/or lattice-invariant transformation) and permute and translate the atoms of the relaxed structures so that they most closely map onto the ideal crystal. If a configuration has already been enumerated by CASM, the DFT data will become associated with that configuration, otherwise the configuration will be added as a new entry in the database. Only one example of duplicate or symmetry-equivalent configurations can be recorded in the database. If multiple structures map onto the same configuration, the conflict can resolved either via a 'lowest-energy' strategy, where the equivalent structure with the lowest energy is kept, or via a 'smallest-deformation' strategy (the default), where the equivalent structure with smallest deformation due to relaxation is kept. You can toggle the strategy via the `--min-energy` flag to `casm import`.

When performing new calculations from the CASM-generated structures I believe that you should be able to use the POSCAR from your original primitive cell (even if it's not in the canonical setting) and the original KPOINTS file for that structure. Those files must exist in `training_data/settings/calctype.default`. The `vasp` python module distributed with CASM will then scale the KPOINTS grid accordingly for each subsequent DFT calculation. It would still be a good idea to check the KPOINTS files for a few different supercells to verify that they are what you expect.

**Comment by Gustautas** [comment]
This is great, thank you.
Nonetheless, as reported in issue #120 `vasp.relax.report` still seems to be not working. A workaround would be using 'casm calc --report', however, `properties.calc.json` then contains coordinates in my original setting. Won't that be a problem?

**Comment by jcthomas** [comment]
Yes, I misspoke. You should use `casm calc --report`.

The setting in properties.calc.json doesn't matter. `casm import` uses a
robust mapping algorithm to find a transformation of the coordinates in
properties.calc.json that maps them back to the setting of prim.json.

**Comment by Gustautas** [comment]
Thanks, everything seems to be working flawlessly. However, after performing MC calculations `--final-POSCAR` option of course writes coordinates in Niggli reduced setting, but I need to do further work in my original setting which I am struggling to convert to. Any suggestions on how to overcome that? Is there any CASM or external tools for such conversions?

**Comment by jcthomas** [comment]
You can create superstructures of POSCAR-type files using `casm super`.  In particular,
`casm super --structure path/to/POSCAR --transf-mat path/to/transf_mat`

The transformation matrix is an integer matrix, whose columns whose columns specify the supercell lattice vectors in terms of the primitive lattice vectors. The file format for a transformation matrix is just as in your original comment above, e.g.,
````
    1   0  -1
   -1   1  -1
    0   0   2
````
For CASM operations, you can assume the primitive-cell lattice vectors form the columns of the matrix **P**=[**a** | **b** | **c**] (note this is the transpose of the lattice-vector matrix in a POSCAR-type file). If **S** is the matrix of supercell lattice vectors, and **T** is the integer transformation matrix, **S** is given by
**S** = **P T**

In your case, you have the CASM-conventional lattice vectors (call it **P1**) and your original setting (call it **P0**).  You can relate them via 
 &nbsp; &nbsp;    **P0** = **P1 T**     &nbsp; &nbsp;  (1)
where **T** is, in this case, the inverse of the `SCEL1_1_1_1_0_0_0` transformation matrix from your original post, so **T** is
````
    0   -1    0
    0    0   -1
    1    1    1
````
This would be the `--transf_mat` that you provide to `casm super` to convert the CASM-conventional primitive cell back to your original setting.

If there are supercells for which you wish to change the setting, it becomes a bit more complicated. If you have a known supercell **S0**, that is related to **P0** (you're original setting) by transf_mat **T0** according to 
 &nbsp; &nbsp;    **S0** = **P0 T0**,      &nbsp; &nbsp; (2)
then the same relation in terms of **P1** is
 &nbsp; &nbsp;    **S0** = **P1** (**T T0**) = **P1 T3**,    &nbsp; &nbsp;  (3)
which you can obtain by substituting Eq. (1) into Eq. (2). **T3** denotes the integer matrix that relates **P1** to **S0**, and **T** is the same matrix as in Eq. (1). 

You can also simply find **T3** directly using the inverse of **P1**, i.e.,
  &nbsp; &nbsp;  **T3** = inverse(**P1**) **S0**  &nbsp; &nbsp;  (4)

If there are situations where you wish to relate different supercell lattice vectors that describe the same lattice (e.g., some **S0** and **S1**), you can do something similar to Eq.(4). **Note:** If the result is not an integer matrix, it means that the lattice vectors do not correspond to the same lattice [although they may correspond to symmetry-equivalent lattices that are related by a rotation or reflection from the point group of the primitive unit cell (applied via left-multiplication with the lattice vector matrix), in addition to the right-multiplied integer matrix].
