### ISSUE TITLE
magnetic cluster expansion?

### ISSUE THREAD

**Issue by DS-Wen** [prisms-center/CASMcode#177]
Hi developers,

I recently read an study of magnetic cluster expansion fulfilled by CASMcode. DOI: 10.1103/PhysRevB.96.165109.
We are very interested in these type of research and would like to realize in our systems. I wonder if there is any detailed instruction on conducting such studies? 
I also have some questions regarding the magnetic cluster expansion:
- does this magnetic cluster expansion share the same correlation function generated by bspecs.json?
- how to setup inputs for magnetic cluster expansion and monte carlo to fit and predict magnetic moments?

Thank you very much,
Dongsheng

**Comment by skk74** [comment]
Hello, 

Sorry for the extreme delay in response to this issue. If you wish to enumerate structures where the spins are colinear this is possible with the publicly available CASMcode. The correlation function generation can be done by giving the magnetic species different names (e.g. Mn1 and Mn2 for spin up and spin down Mn). In the SPECIES file you can assign the atomic MAGMOM tag for VASP that corresponds to Mn1 and Mn2 accordingly. If this answer is not specific enough please do not hesitate to contact my email skolli@ucsb.edu

Again sorry for the delayed response.

**Comment by DS-Wen** [comment]
Thanks! 

Then I'm a bit confused regarding the cluster expansion on the collinear calculation results.I seems to me that only the sign of that magnetic moment of the atom matters (say +1 for Mn1 and -1 for Mn2 with different MAGMOMs, right?). When some structures were relaxed to a state in which all Mn1 and Mn2 sites have the same magnetic moment, how do we deal with those sites? 

Thanks,
Dongsheng

**Comment by skk74** [comment]
The SPECIES file only dictates on how the MAGMOMs are initialized in the VASP calculation. VASP calculations that relax significantly away from the starting configuration should not be used as training data in the cluster expansion because the configuration interpreted by the cluster expansion degrees of freedom is not representative of the structure associated with the relaxed energy. 

If you would like to account for non magnetic configurations in your cluster expansion you would have to add a third species Mn3 with a MAGMOM of 0.

**Comment by DS-Wen** [comment]
That's really helpful. Thanks!
