### ISSUE TITLE
Dealing with periodic boundary conditions during ECIs fitting.

### ISSUE THREAD

**Issue by Gustautas** [prisms-center/CASMcode#178]
Dear developers,
I have obtained very unintuitive results while checking my ECIs fit. As you can see from the plot, it seems to be not converging at all.
![image](https://user-images.githubusercontent.com/56716523/73639415-0065a200-4675-11ea-8ab5-2935ce7f5156.png)

My system has rhombohedral lattice and I use 2x1x1 supercells (separated with a solid line in the image) for fitting.
![image](https://user-images.githubusercontent.com/56716523/73637824-d1016600-4671-11ea-8bba-a48eb8d61b25.png)
For generating basis set I simply use:
```
{
  "basis_functions" : {
    "site_basis_functions" : "occupation"
  },
  "orbit_branch_specs" : {
    "2" : {"max_length" : 15.5},
    "3" : {"max_length" : 10.0},
    "4" : {"max_length" : 6.0}
  }
}
```
I get multiple basis functions corresponding to the "same" (e.g. A1-A2) pair:
```
...................................
      ** 42 of 679 Orbits **  Orbit: 2 39  Points: 2  Mult: 6  MinLength: 9.5092958  MaxLength: 9.5092958
            Prototype of 6 Equivalent Clusters in Orbit 42
                                 0.8516000    0.8516000    0.8516000 A B
                                 1.1484000    0.1484000    0.1484000 A B
....................................
      ** 145 of 679 Orbits **  Orbit: 2 142  Points: 2  Mult: 2  MinLength: 15.2649263  MaxLength: 15.2649263
            Prototype of 2 Equivalent Clusters in Orbit 145
                                 0.8516000    0.8516000    0.8516000 A B
                                 0.1484000    0.1484000    0.1484000 A B
....................................
```
which is normal, since depending on the supercell these sites can be different.
The problem is that after fitting I find an ECI for orbit 145, but not for 42. Which, despite causing complication while plotting convergence, raised the suspicion that there might be problems with periodic boundary conditions. Is it normal behavior? Can I be sure that double-counting (A1-A2, C3-A3 cases), self-interactions (C1-C1 case) etc. are strictly prohibited and are not influencing the fitting procedure? Same thing for triplets and quadruplets, of course.
Thank you.

**Comment by skk74** [comment]
Hello sorry for the extreme delay on responding to this issue. 

One thing to check is to make sure that your fitting procedure is correct. It might be the case that the weighting of each configuration that you are using is not what you believe it is. The details of the fitting procedure can be found by running the command casm-learn --settings-format. The enumeration of basis functions that you label the "same" is totally normal as you have pointed out. 
When it comes to fitting there are no constraints imposed by default on the basis functions that are allowed to have non zero ECI values. This is because the fitting procedure is completely independent from the basis function generation. If you wish to impose such constraints on the genetic algorithm you may do so using the "fix_on" and "fix_off" tags in the settings file for your fitting procedure. 
The behavior you observed (i.e. selected 145 but not for 42) is definitely within the realm of possibility for an unbiased fitting procedure and is not erroneous behavior. 

Again sorry for the delay in response

**Comment by Gustautas** [comment]
Thanks
