### ISSUE TITLE
Clarity on casm update --max-va-frac 

### ISSUE THREAD

**Issue by bmedeir1** [prisms-center/CASMcode#179]
Hi, 

When using casm update, does the --max-va-frac option refer to the general vacancy concentration or is it in addition to the vacancies in the configuration itself?  For example, if one of my configurations has a vacancy concentration of 0.002 and I set a max-va-frac of zero, will this make it unable to map the relaxed basis to its corresponding configuration?

**Comment by jcthomas** [comment]
The `--max-va-frac` and `--min-va-frac` options refer to the overall fraction of sites of the ideal crystal that are determined to be vacant when the relaxed DFT structure is mapped onto the ideal crystal. 

In many cases, the supercell volume of the relaxed cell can be fully determined by number of atoms in the DFT calculation. For example, if `prim.json` is a HCP cell (2 sites), and each site can be either A or B species, then a DFT result comprising 50 atoms (22 A specie and 28 B specie) must be a configuration of a supercell that is 25 times the HCP primitive cell (50 atoms/2 sites). 

If every site in `prim.json` can host a vacancy, the supercell volume it not specified by the number of atoms. In the preceding example, a DFT calculation with 50 atoms could indicate a Vol-25 supercell with 0 Vacancy fraction, or a Vol-26 supercell with ~3.8% Vacancy fraction, or a Vol-100 supercell with 50% Vacancy fraction. 

When vacancies are allowed at every sites, and the supercell volume cannot determined by the number of atoms, CASM falls back on heuristic assumptions about the maximum number of vacancies and the degree of volume relaxation (actual, spatial volume, not the integer multiple of the primitive cell) to reduce the number of supercells considered during mapping.

If you set `--max-va-frac` to zero, CASM may be able to find a mapping that satisfies that constraint, but it may not be the best mapping, and it will not correspond to the starting configuration. 

If `casm update` is very slow, you could set `--min-va-frac` and `--max-va-frac` to form some very tight bounds around the vacancy composition that you want to identify the structure with.  **However**, 0.002 is very dilute, so I assume that you may have a very large supercell, and the mapping will still take a very long time.  If that is the case, you can try treating the structure as an imported configuration via `casm import`, with the `--ideal` flag. The `--ideal` import option uses a different strategy than the general mapping algorithm and is much faster for large supercells. However, you may need may need to edit the lattice vectors and relaxed coordinates in `properties.calc.json` to be the ideal values of the starting configuration in order to get the ideal import to work.

As an aside, there will be much finer control of this behavior in version 0.4, which will be released in the coming months.

**Comment by bmedeir1** [comment]
Ok, this is very helpful. Thank you!
