### ISSUE TITLE
Batch Job Submission for bset -u and learn commands

### ISSUE THREAD

**Issue by darnoceloc** [prisms-center/CASMcode#180]
Is there any recommended protocol for executing casm bset -u '-f' and casm learn -s via batch jobs?

For the bset -u -f command, the output (core.XXXXX), error files have been quite large, ~4 GB and used memory outgrew requested memory.

When executing the job via a developmental session (as I had previously done successfully when utilizing smaller clusters) Initialization error: Cannot load symbol make_Ceria_Clexulator.

The casm learn -s jobs resulted in:

-- casm usage --

casm [--version] <command> [options] [args]

available commands:
  bset
  composition
  enum
  files
  format
  help
  import
  init
  monte
  perturb
  query
  ref
  run
  select
  settings
  status
  super
  sym
  update
  version
  view

Below is an example of my submission scripts.

#!/bin/bash

#SBATCH --job-name=Basis_set_update
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH -o out_%j
#SBATCH -e err_%j
#SBATCH --ntasks=128
#SBATCH --ntasks-per-socket=16
#SBATCH --ntasks-per-node=32
#SBATCH --nodes=4
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=7000mb
#SBATCH --time=96:00:00

cd $SLURM_SUBMIT_DIR

module purge
module load gcc/5.2.0
module load casm/0.2.0

srun --mpi=pmix_v2 casm bset -u -f > job.log

srun --mpi=pmix_v2 casm learn -s fit_1_ga.json > job.log

**Comment by darnoceloc** [comment]
Note, the version of casm installed on the hpc as a module doesn't correspond to the version of casm installed as a conda environment.

**Comment by jcthomas** [comment]
Prior to version 0.3.X, `casm learn` must be invoked using `casm-learn` (note the hyphen), which calls a python script.

I don't see any problem with your invocation of `casm bset`. However, it shouldn't be necessary to run `casm bset` as a batch job. None of the `casm` commands run on more than a single thread. If there are so many basis functions that your process is running out of memory, you will need to reduce the length specifications in your `bspecs.json` file. If there are particular interactions that you want to make sure are included, you can specify clusters manually via the `"orbit_specs"` tag in `bspecs.json`. For more information, take a look at `casm format --bspecs`.

As an aside, I'd suggest, if possible, to avoid mixing versions of casm within a project. In particular, anything having to do with the basis set or correlation values **may** give unexpected behavior if you operate on a single project with both 0.2.0 and 0.3.X.

From a diagnostic perspective, it would be useful to know if your job script fails even when the number of basis functions is small, and what type of error output is produced.

**Comment by darnoceloc** [comment]
Is there a suggested limit to cluster sizes/radii and protocol for utilizing occupation vs. chebyshev along with other configurations of bspecs.json?
Furthermore, does the eci.__tmp file verify whether or not the basis functions were properly updated? What casm commands modify/update this file?
I also assume this file (and no other) specifies the number of non-zero ecis?

**Comment by jcthomas** [comment]
`"occupation"` basis functions typically perform better (i.e., converge faster) when one species is dilute, and `"chebyshev"` typically perform better when all species are non-dilute. However, these are just general guidelines.

When you do a fit using a feature selection method like the genetic algorithm, the result will be a population of many fits, each with a different set of non-zero ECIs. You can select one of these to use in your project by running `casm-learn -s <settings file> --select <Index>`. The maximum number of nonzero ECIs is the size of the basis set. The basis set size is wholly determined by `bspecs.json`. There are no universal guidelines for cluster specifications, but it is often a good idea to start small (e.g., 50-200 basis functions, maybe mostly pairs, a handful of triplets, and a few quadruplets) and only increase the number of clusters as needed.  You can further restrict which ECI are allowed to be nonzero via the casm-learn settings file.

You can create different settings profiles for your project and associate a different fit with each profile. To do this, you can run `casm settings --new-eci <give-it-a-name>` and then use `casm-learn` to select a fit for the current profile. The starting profile is called 'default'.   `eci.__tmp` is a temporary profile that is created by `casm-learn` for the purpose of checking the convex hull. It would normally be deleted before `casm-learn` terminates, but `casm-learn` is crashing before that happens. Because of this, you may need to reset your project's current settings profile via `casm settings --set-eci default`.

**Comment by darnoceloc** [comment]
I am performing the relaxations again with SCAN+U to more accurately reproduce electronic structure properties. 
Is it generally accepted that there should be ~10 times more structures than non-zero eci to obtain a high quality fit?
Would utilizing PBE+U and 35 structures vs. SCAN and 200 structures result in two orders of magnitude difference in CV score (in favor of former).

**Comment by darnoceloc** [comment]
No comment?

**Comment by bpuchala** [comment]
About 10x more data points than non-zero eci is a decent rule of thumb for getting started, but it is no guarantee of a good fit. In general, it's probably not a good idea to speculate too much about any particular fit without seeing the data.

**Comment by darnoceloc** [comment]
What sort of algorithm is utilized to generate the various cluster orbits that each span the lattice? How about for structure enumeration as function of supercell size? Are any graph algorithms implemented within the essential steps of casm project workflow?

**Comment by bpuchala** [comment]
The cluster orbits are generated starting with the "max length" cutoff values to determine a local neighborhood of potential sites. Then the algorithm works recursively to add 1 site clusters, 2-site clusters, etc. by adding candidate sites to existing clusters and then check if an equivalent cluster exists or not.

There are a couple methods included for generating configurations. The "ConfigEnumAllOccupation" method counts over potential orderings in a supercell and then applies symmetry operations consistent with the prim and the supercell to check if the ordering is the unique "canonical" form (essentially represented by the lexicographically greatest occupation indices) or is an equivalent to the canonical form or is a supercell of a more primitive equivalent ordering.  

A couple of the genetic algorithm based searches for cluster expansion fits are graph algorithms. Look at `casm learn --settings-format` for "IndividualBestFirst" or "PopulationBestFirst".

**Comment by darnoceloc** [comment]
Are there unique algorithms specifically designed for these applications implemented in casm or are they mostly adopted from conventional computer science approaches, i.e., graphs, trees, heaps, etc.?

**Comment by skk74** [comment]
In general the algorithms in CASM have to be tailored to the specific data structures used in the code. As frequently as possible, we use STL data structures and algorithms to reduce repetitive coding. If you would like an in depth interactive discussion of some of the algorithms in CASM please email me at skolli@ucsb.edu and maybe we can set up an online meeting.
