### ISSUE TITLE
0.3.x compiling error with <bits/mathdef.h> 

### ISSUE THREAD

**Issue by qinlene** [prisms-center/CASMcode#183]
Hi,

I tried to build casm 0.3.x (on ubuntu 18) following the instructions on INSTALL.md. I got some error regarding <bits/mathdef.h>:

```shell
In file included from /home/lene/.local/conda/envs/casm_dev/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/math.h:47:0,
                 from /home/lene/.local/conda/envs/casm_dev/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:45,
                 from ./include/casm/CASM_global_definitions.hh:5,
                 from ./include/casm/app/casm_functions.hh:5,
                 from apps/ccasm/ccasm.cpp:1:
/usr/include/bits/mathdef.h:19:3: error: #error "Never use <bits/mathdef.h> directly; include <complex.h> instead"
 # error "Never use <bits/mathdef.h> directly; include <complex.h> instead"

```

I realize the compiler uses the system include file, so I change the CASM_CXXFLAGS to include file in /conda/envs/casm_dev/x86_64-conda_cos6-linux-gnu/sysroot/usr/include, but the compiler still use the system include file. 

Can anyone tell me how to solve it? 
Thanks in advance.

**Comment by bpuchala** [comment]
If you are just trying to use CASM, then you could follow the instructions [here](https://prisms-center.github.io/CASMcode_docs/pages/installation.html) to install CASM as a conda package.

Otherwise, it's not clear from the what is shown alone what is causing the issue. One way to troubleshoot os specific issues by installing CASM in a clean docker container for a particular os. Our unit tests are run against ubuntu 14.04, trusty, and centos:6.
