### ISSUE TITLE
About feature select and neural network

### ISSUE THREAD

**Issue by q654262498** [prisms-center/CASMcode#184]
Dear CASM developers,

Through the CASM learning process,we found that CASM is an excellent software, also we’re quite interested in your group’s research in the combination of CASM and machine learning algorithms,and we’re working on this field,during our learn process,a few of difficulty has show up and we’d like ask you some question,hoping get answer form you.
1.During our use of CASM,do we need download VASP,connect it with CASM,and the file config_list.json will update by CASM or VASP  automatically,is it how it work?
2.After CASM run the genetic algorithm and select the features,how can we get the selected features,whether the features selected by this step can be used in future nonlinear computing methods,such as :Neural network input characteristics?
3.About on the use of neural network to calculate configurational energy of multicomponent crystals,do we only need to train one site of neural network,and the rest of the site’s neural network will same as the former training model.
Although we also have some of our own thoughts and ideas about the above problem in the learning process,we still feel very confused about those question and hoping that we can get answer form you.
Once again, we would like to express our heartfelt thanks and pay tribute to your scientific research.

**Comment by skk74** [comment]
Hello  sorry for the delayed response:

1) Yes during your using of CASM you will need some DFT code to calculate energies for the structures you enumerate. We have run a lot of testing with VASP because that's what we use in the group and I suggest that as a first choice.  We also have limited support on Seqquest and Quantum Espresso.  The config_list.json file gets updated on the casm commands ```casm enum``` , ```casm import``` and ```casm update```. If you use CASM to submit your DFT jobs to a compute cluster then running ```casm update``` will update the config_list.json with the appropriate data provided the calculations were completed without error. 
2. The selected features from the genetic algorithm are written to a file called eci.json that is deep in the cluster_expansions portion of you casm project. Information regarding the basis functions that were used in the model and which were selected to have non zero ECI values is present there. 
3. Unfortunately, I do not quite understand your question. I'm not sure what you mean by training one site of the neural network. You can use the correlation values for the configurations of interest (these can be output by using ```casm query -k corr``` ) as features in your custom neural network code.

**Comment by q654262498** [comment]
Thanks for your answer,to the third question,we reorganized the expression,questions are as follows.
1.we are very interested in transforming the configuration energy into the sum of site energy and using the local correlation function as the input feature of the machine learning method. And we’d like to try it out, but from our practice, we need local site-centric correlation functions ,and use them as input features,but we can’t be able to find the information directly from the tutorial demonstration provided by CASM on GitHub, so we’d like to ask you about how to operate CASM will let us get local site-centric correlation functions.
2. We also want to ask you, in the process of site energy neural network calculation, if It is correct that the site energy training label given by the DFT calculation of VASP?
We are looking forward to your reply in your earliest convenient.
