### ISSUE TITLE
Monte Carlo Susc of Correlations

### ISSUE THREAD

**Issue by tallakahath** [prisms-center/CASMcode#21]
Even if I specify data: measurements: quantity: all_correlations, I do NOT get any susceptibility of correlations. I desperately need these!

My current 'hack fix' is to output the full trajectory and calculate after...

**Comment by bpuchala** [comment]
We made a decision not to output the entire covariance matrix since it is not as typical a use case and can blow up quickly. So outputting all the observations and calculating directly is the current solution. We can consider an option to calculate and output the full covariance matrix, or some way to specify particular elements. What would be your ideal situation?

**Comment by tallakahath** [comment]
Ideally, I'd like two flags under 'measurements:quantity':
'non_zero_eci_covariance' and "all_eci_covariance', which output the
covariance matrix of only those correlations w/nonzero ECIs, and the full
covariance matrix, respectively. I understand that few people besides me
may use it, though it would allow CASM to be used with more general Reverse
Monte Carlo schemes, too.
