### ISSUE TITLE
CSVs have a whitespace between # and the first field that breaks pandas

### ISSUE THREAD

**Issue by tallakahath** [prisms-center/CASMcode#22]
Specifically, the header of ANY csv file produced throughout CASM has:
# first_field  second_field  third_field etc

The problem is that this causes pandas.read_csv to do the following:

> raw = pd.read_csv("my_file.csv", delim_whitespace=True) # delim_whitespace is necessary as our CSVs lack commas
> raw.columns
> < Index([u'#', u'first_field', u'second_field', u'third_field', etc ... ])

Meaning all the column indexing gets shifted over by 1. My current solution is to, by hand, remove that initial whitespace. But, why is it even there?

**Comment by bpuchala** [comment]
I believe some of the reason was to also make it work nicely with gnuplot? (I don't use gnuplot, so I'm not sure about this). 

Try:
```
with open(file, 'r') as f:
    f.read(1)
    df = pandas.read_csv(f, sep=' *', engine='python')
```

As a reminder, we already have code for reading 'casm select' output using 'casm.project.Selection'.

**Comment by tallakahath** [comment]
Can we have a project_settings for "header_space: false", because if the
space is necessary for gnuplot but breaks pandas this seems like a matter
of 'what does the user want to primarily use'.

**Comment by jcthomas** [comment]
The `casm query` csv output is primarily intended to be human readable,
which is why column headings are (for the most part) right-aligned with the
columns.

I'm not opposed to getting rid of the leading '#' in the header, if it
doesn't break compatibility with common analysis codes, or we could make it
a command-line option (possibly along with delimiter character).

For more arcane formatting requirements, it's probably easier for to use
something like `sed`, or just using the JSON output instead.

**Comment by tallakahath** [comment]
I've pretty much taken to using json *almost* everywhere, however,

When I do "casm query -k comp_n(A) -o foo.csv" it gives me columns of:

"configname selected comp_n(A)"

But if I do -o foo.json it instead gives me keys of:

"configname, selected, comp_n"

Where comp_n is a 2d array formatted in a really frustrating fashion. Even
when I specify "comp_n(A)", where 'A' is a valid component (my system
literally has A/B, not 'real' elements).

So using the jsons doesn't really work for me.

**Comment by bpuchala** [comment]
What is your preferred output?

The 2d JSON representation for 1d arrays is another place where the output style was optimized for human readability rather than code readability. I think the output of a 2d array output for 'comp_n(A)' was just an oversight.

Personally, I think human readable output should be obtained via a CLI or Python command and not baked into the file formats, but that's not what we've been prioritizing in the past.

**Comment by tallakahath** [comment]
The 2D JSON thing makes it both awkward to read as a human and as a
machine, because now you need to parse an array from within an array of
arrays. Why can't the JSON mirror the CSV and have different fields for
each comp_n the way the CSV breaks out '-k comp_n' into "comp_n(A)
comp_n(B) etc"?

Basically, I'd like the JSON to be like a CSV but in JSON format, rather
than having an inherently different structure underneath, at least, as long
as this makes sense. E.g. comp_n is easily and logically broken into diff
columns, but a matrix that exists per-structure (e.g. to describe strain)
should be its own 'object' (so here you'd still have a single list of
matrices rather than some weird set of columns).

**Comment by goirijo** [comment]
The leading ```#``` symbol has caused me to waste quite a bit of time. I think an average user is going to expect the number of headers in a ```csv``` file to match the number of columns in it.
