### ISSUE TITLE
Can CASM account for long-range interactions, including electrostatic energy?

### ISSUE THREAD

**Issue by sjtuzhanglei** [prisms-center/CASMcode#244]
Dear CASM developer,

We know that cluster expansion is great for short-range interactions fitting. Does CASM implement functions describing long-range interactions, like electrostatic ones? 

Noticed that the community developed reciprocal-space cluster expansion, or fitting energy excluding the Madelung energy (and add back later on for convex hull). Does CASM has this capability?

In general, how to check if long-range interactions is fitted well in a current cluster expansion bset?

Thanks,

**Comment by bpuchala** [comment]
CASM does not currently implement these. For checking, overall cv score and rms error are relevant. Some more specific checks that you could do would be to check the fitting error (i.e. 'clex(formation_energy)' - 'formation_energy') vs trends such as 'volume_relaxation' or 'relaxation_strain' or for particular configurations / Monte Carlo cells you expect to be problematic due to ordering at a longer length scale than the cluster expansion interactions.

**Comment by sjtuzhanglei** [comment]
Hi Brain, 

What would be the correct format of query for 'clex(formation_energy)' - 'formation_energy' ?

I tried but it failed with segmentation fault.

casm query -k comp "sub(clex(formation_energy), formation_energy)" relaxation_strain -c CALCULATED
Print:
   - comp
   - sub(clex(formation_energy), formation_energy)
   - relaxation_strain

Segmentation fault


casm query -k comp sub(clex(formation_energy),formation_energy) relaxation_strain -c CALCULATED
-bash: syntax error near unexpected token `('

Thanks,
