### ISSUE TITLE
KPAR is ignored

### ISSUE THREAD

**Issue by max-radin** [prisms-center/CASMcode#44]
The vaspwrapper ignores any KPAR value specified in `settings/$CALCTYPE/INCAR`. Users can bypass this by setting KPAR in relax.json rather than INCAR.

**Comment by bpuchala** [comment]
@tallakahath Could you also address this?

**Comment by tallakahath** [comment]
Oh, I brought this up a while back, and the conclusion was that this behavior is intentional. Do we want to change this?

**Comment by tallakahath** [comment]
For now I've fixed it such that:

- If NPAR or NCORE is set in relax.json, it overrides the INCAR
- If neither NPAR or NCORE is set in relax.json, the INCAR is obeyed
- If KPAR is set in relax.json, it overrides the INCAR
- If KPAR is not set in relax.json, the INCAR is obeyed

This means an empty/not-present KPAR entry in relax.json won't blank out an INCAR's KPAR, but a relax.json KPAR will override the INCAR's KPAR.

Overall, I'd like to (at some point) reexamine how we do KPAR, and NCORE/NPAR, to implement some better automatic settings (e.g. some clusters want you to request whole nodes, some don't, KPAR should scale with an approx. IBZKPT so that KPAR >= no. of kpts, etc).
