### ISSUE TITLE
lib/libcasm.so: undefined reference to `boost::filesystem::detail

### ISSUE THREAD

**Issue by Anu-Maria** [prisms-center/CASMcode#61]
I am trying to install CASM code . I could successfully run configuration checks and configure all the binaries. But while giving the scons install command I end up with the following error. 
lib/libcasm.so: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
scons: *** [bin/casm] Error 1
scons: building terminated because of errors.
Can you please help me to fix this error

**Comment by bpuchala** [comment]
This is usually due to boost being compiled without c++11 and casm being compiled with it.  If this is the case, setting the environment variable: `export CASM_BOOST_NO_CXX11_SCOPED_ENUMS=1` before compiling with scons should solve the problem. What is `scons configure` output?

**Comment by Anu-Maria** [comment]
I have already set the the environment variable: export
CASM_BOOST_NO_CXX11_SCOPED_ENUMS=1
While giving scons configure I am getting the following output:

scons: Reading SConscript files ...
Checking for c++11... yes
Checking for C library z... yes
Checking for C library dl... yes
Checking for C library dl... yes
BOOST_PREFIX: None
(cached) Checking for boost headers... (cached) found
/usr/local/include/boost... (cached) yes
Found boost library: boost_system as: boost_system(cached) yes
Checking for C library boost_system... yes
Found boost library: boost_filesystem as: boost_filesystem(cached) yes
Checking for C library boost_filesystem... yes
Found boost library: boost_program_options as:
boost_program_options(cached) yes
Checking for C library boost_program_options... yes
Found boost library: boost_regex as: boost_regex(cached) yes
Checking for C library boost_regex... yes
Found boost library: boost_chrono as: boost_chrono(cached) yes
Checking for C library boost_chrono... yes
Found boost library: boost_timer as: boost_timer(cached) yes
Checking for C library boost_timer... yes
Found boost library: boost_unit_test_framework as:
boost_unit_test_framework(cached) yes
Checking for C library boost_unit_test_framework... yes
Checking for Boost version >= 1.54... yes
Checking if BOOST_NO_CXX11_SCOPED_ENUMS setting is correct... (cached)
Was set via environment variable CASM_BOOST_NO_CXX11_SCOPED_ENUMS...yes
Checking for Python module 'numpy'...  yes
Checking for Python module 'sklearn'...  yes
Checking for Python module 'deap'...  yes
Checking for Python module 'pandas'...  yes
Checking for Python module 'pbs'...  yes
Configuration checks passed.

**Comment by bpuchala** [comment]
What compiler are you using? I've been getting some TravisCI tests ready, but don't have it all setup yet.  I've been setting them up with `clang-703.0.31` and `gcc-4.8.5` for compilers; and boost-1.55, compiled without c++11 with `CASM_BOOST_NO_CXX11_SCOPED_ENUMS`.  When I have a chance to get back to it I can try expanding the matrix to include more recent versions, but in the meantime perhaps you can try using one of those if you are not already?

**Comment by Anu-Maria** [comment]
Previously I was using gcc - 4.8.4 compiler and  boost-1.55. Now I have
upgraded the gcc compiler to gcc 4.8.5 version. Still the error is
persisting while doing CASM installation.

**Comment by DS-Wen** [comment]
I may have the same problem in compiling. My gcc version is 5.2.0 and the boost, 1.64. Scons configure runs well but the scons install command gave me this message:
/apps/rhel6/gcc/5.2.0/bin/g++ -o src/casm/version/version.os -c -DNDEBUG -O3 -std=c++11 -Wno-deprecated-register -Wno-deprecated-declarations -DEIGEN_DEFAULT_DENSE_INDEX_TYPE=long -DBOOST_NO_CXX11_SCOPED_ENUMS -Wno-unused-parameter -DNDEBUG -O3 -DGZSTREAM_NAMESPACE=gz -fPIC -Iinclude src/casm/version/version.cc
/apps/rhel6/gcc/5.2.0/bin/g++ -o bin/casm -Wl,--rpath=\$ORIGIN/../lib -z origin apps/casm/casm.o -Llib -L/home/wen94/boost/lib -lboost_system -lboost_filesystem -lboost_program_options -lboost_regex -lboost_chrono -ldl -lz -lcasm
lib/libcasm.so: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&)'
lib/libcasm.so: undefined reference to `_ZN5boost15program_options16validation_error12get_templateB5cxx11ENS1_6kind_tE'
lib/libcasm.so: undefined reference to `_ZNK5boost15program_options18option_description16format_parameterB5cxx11Ev'
lib/libcasm.so: undefined reference to `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
lib/libcasm.so: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
lib/libcasm.so: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
lib/libcasm.so: undefined reference to `_ZN5boost15program_options3argB5cxx11E'
lib/libcasm.so: undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
lib/libcasm.so: undefined reference to `_ZNK5boost15program_options18option_description22canonical_display_nameB5cxx11Ei'
lib/libcasm.so: undefined reference to `boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
lib/libcasm.so: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
lib/libcasm.so: undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
lib/libcasm.so: undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
lib/libcasm.so: undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
lib/libcasm.so: undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool*, int)'
lib/libcasm.so: undefined reference to `boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>)'
lib/libcasm.so: undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
collect2: error: ld returned 1 exit status
scons: *** [bin/casm] Error 1
scons: building terminated because of errors.
Could you please help me identify the problem?

**Comment by Anu-Maria** [comment]
I have uninstalled the boost and reinstalled it from the source code by compiling with C++11 by using the command ./b2 -std=C++11. Now it is running without error.
