### ISSUE TITLE
Reading outputs from Monte Carlo(MC) simulations

### ISSUE THREAD

**Issue by DaehyeonChoi** [prisms-center/CASMcode#67]
Hi
Thanks for the previous comment on my question

Here I've got some trouble in analyzing results from MC simulations.

Firstly, I prepared 'input_MC.json' file to start MC and typed 'casm monte -s input_MC.json'.
The process seemed perfect and I've got several folders named 'conditions.<#>' and 'occupation_key.json' and 'results.json'. And each 'conditions.<#>' folders, 'conditions.json', 'initial_state.json', 'final_state.json', 'observations.json.gz' and 'trajectory.json.gz' exist.

Also I've tried '--initial-POSCAR', '--final-POSCAR' and '--traj-POSCAR' for certain condition # and checked the results from these commands.

Problem is that only I could find were POSCARs, which contain information about structure. I expected information about sort of energy, which is predicted from previous Cluster expansion results (selected set of ECIs). For example, at fixed temperature, with varying chemical potential, find equilibrium states of supercell.

It seems that reading 'results.json' file is the key for my problem, but it's difficult for me and even I'm not sure it will be the key.

It will be really grateful for help.
Thanks

**Comment by bpuchala** [comment]
The `results.json` file contains a summary of the conditions run at (T, chem pot, etc.) and results (means and estimated precision) at each condition.  The convergence criteria and precision calculation follow `A. van de Walle, M. Asta, Modell. Simul. Mater. Sci. Eng. 10, 521 (2002).` If you ran at three conditions, with varying temparture, a subset of your results, re-ordered for clarity, might be:

The conditions (Temperature, Beta = 1/(kB*T), parametric chemical potential):
```
{
  "T" : [ 300.000000000000, 400.000000000000, 500.000000000000 ],
  "Beta" : [ 38.681686502500, 29.011264876875, 23.209011901500 ],
  "param_chem_pot(a)" : [ -1.140000000000, -1.140000000000, -1.140000000000 ],
  ...
```

Whether the calculation equilibrated, how many samples it took before it equilibrated, whether it converged to the requested precision, how many samples (the "number of averaging samples") are included in the mean and precision calculations:
```
  ...
  "is_equilibrated" : [ true, true, true ],
  "N_equil_samples" : [ 9, 9, 5 ],
  "is_converged" : [ true, true, true ],
  "N_avg_samples" : [ 991, 991, 995 ],
  ...
```

The mean compositions and calculated precision:
```
  ...
  "<comp(a)>" : [ 0.342163836670, 0.360150130322, 0.379927070193 ],
  "prec(<comp(a)>)" : [ 0.000417264894, 0.000503214144, 0.001079702501 ],
  "<comp_n(O)>" : [ 0.684327673340, 0.720300260645, 0.759854140386 ],
  "<comp_n(Va)>" : [ 1.315672326660, 1.279699739355, 1.240145859614 ],
  "<comp_n(Zr)>" : [ 2.000000000000, 2.000000000000, 2.000000000000 ],
  "prec(<comp_n(O)>)" : [ 0.000834529788, 0.001006428288, 0.002159405003 ],
  "prec(<comp_n(Va)>)" : [ 0.000834529788, 0.001006428288, 0.002159405003 ],
  "prec(<comp_n(Zr)>)" : [ 0.000000000000, 0.000000000000, 0.000000000000 ],
  ...
```
The mean formation energy (eV per unit cell) and precision:
```
  "<formation_energy>" : [ -0.539574208746, -0.555986548604, -0.572913494569 ],
  "prec(<formation_energy>)" : [ 0.000284743497, 0.000493588842, 0.001145406416 ],
```

The mean potential energy (eV per unit cell), `(formation_energy - param_chem_pot.dot(comp))`, and precision:
```
  ...
  "<potential_energy>" : [ -0.149507434942, -0.145415400036, -0.139796634549 ],
  "prec(<potential_energy>)" : [ 0.000082849583, 0.000143565570, 0.000174541317 ],
  ...  
}
```
and so on for any other properties you requested to sample.  If you request `csv` output, it is the same data, just organized into columns instead of JSON.

The `observation.json.gz` files, if requested, contains all the individual observations that were made and used to calculate the means and precision, for each condition.

The `initial_state.json`, `final_state.json`, and the `trajectory.json.gz` file, if requested, contain a list of occupation values in the Monte Carlo supercell at the start and end of the calculation, and at each sample. They are what is read back into CASM to create the POSCARs for POSCAR creating commands.

**Comment by DaehyeonChoi** [comment]
Thanks for your clear answer!

It really helps me out with understanding results.csv.
