### ISSUE TITLE
Issue generating cluster orbit

### ISSUE THREAD

**Issue by MSTitus** [prisms-center/CASMcode#73]
All, I am trying to generate basis functions for a relatively large supercell (32 atoms, 8 dofs). I receive the following error with the attached prim.json and bspecs.json input file:

[bspecs.txt](https://github.com/prisms-center/CASMcode/files/1249622/bspecs.txt)
[prim.txt](https://github.com/prisms-center/CASMcode/files/1249624/prim.txt)

-- Generate: Cluster orbits -- 
CRITICAL ERROR: In SymGroupRep::set_rep(), representation already exists for operation 8.
                Exiting...

Note that in the mainclust11 from years back, I had no problem generating basis functions with this same unit cell. 

The nearest neighbor pair is ~3.88A, and this error appears when I increase the max_length above that value. max_length values below 3.88A only generates the point clusters (of course).

I've messed around with crystallography_tol, but this did not change anything. 

I'm not exactly sure what the error means, and I don't understand it in the context of SymGroupRep.cc, so any help would be appreciated.

**Comment by jcthomas** [comment]
Your prim is very close to the default tolerance (if I decrease `crystallography_tol` to 0.5E-05, it finds monoclinic symmetry, instead of rhombohedral). However, it seems apparent that `crystallography_tol` is not propagating everywhere that it should. 

I haven't looked into it fully, but it might also be possible to increase the numerical stability of the algorithm that is failing so that this is less likely to cause an issue.

In the meantime, I was able to suppress the error by increasing the precision of the prim you provided. 

Please see attached:
[prim.sym.json.txt](https://github.com/prisms-center/CASMcode/files/1249754/prim.sym.json.txt)
