### ISSUE TITLE
Question about occupation variables & ECI scale

### ISSUE THREAD

**Issue by DaehyeonChoi** [prisms-center/CASMcode#80]
Dear CASM developers

Hello

The code really has helped me with my research.

But here I've got sort of simple problems here.

1. Normally in binary cluster expansion (Like (metal A or Vacancy) in the system), the atomic species are given '+1 and -1' as so called occupation variables.  I've tried to find them in my cluster expansion, and I've found that in $ROOT/.casm/config_list.json, "occupation" line shows some kind of variables as [1, 0, 0, .....,0]. I'm not sure they are what I've tried to find.

2. With the command, casm-learn -s fit_1_ga.json --hall --indv 0 --format details, we can check the eci values in the '0' set. I've checked them, but it's quite unsure that whether they are written in eV or meV/the reference formula unit. I've supposed that what I've got might be written in eV/formula unit. Actually, I want to be checked what I've got.

Please give me your advice. I will be really grateful for your help.

Thanks

**Comment by jcthomas** [comment]
Glad to hear you're finding CASM to be useful!

1) The `"occupation"` field in `$ROOT/.casm/config_list.json` stores indices into the list of allowed occupants. These are converted into site basis functions internally in order to evaluate the correlations.

You can use `casm bset --function` to get a read-out of the values and formulae that go into the cluster expansion.  The first part of the output provides information about the site basis functions (for a binary alloy, these correspond to the spin or occupation variables)

Example:
````
Asymmetric unit 1:
  Basis site 0:
                 0.0000000    0.0000000    0.0000000 W Al
        \phi_0_0[W] = -1.0000000,       \phi_0_0[Al] = 1.0000000
  Basis site 1:
                 0.6666667    0.3333333    0.1250000 W Al
        \phi_1_0[W] = -1.0000000,       \phi_1_0[Al] = 1.0000000
````
These are the site basis function for two equivalent sites (they belong to the same asymmetric unit site). Each site can host either W or Al. Evaluating function \phi_0_0 for a W occupant gives a value of -1, while evaluating the same function for an Al occupant gives a value of +1. The site basis functions are named \phi_${site_index}_${function_index}, where for a binary alloy, ${function_index} is always 0 (because there is only one function per site). 

The second part of the output of `casm bset --function` gives the cluster basis functions, which are written as products of the site basis functions
Example:
````
      ** 5 of 10 Orbits **  Orbit: 2 0  Points: 2  Mult: 2  MinLength: 3.5879999  MaxLength: 3.5879999
            Prototype of 2 Equivalent Clusters in Orbit 5
                       0.3333333    0.6666667    0.8750000 W Al  basis_index: 7  clust_index: 0 
                       0.0000000    0.0000000    1.0000000 W Al  basis_index: 0  clust_index: 1 

            Basis Functions:
              \Phi_5 = \phi_7_0(s_0)\phi_0_0(s_1)
````
where `\phi_7_0(s_0)` indicates "function 0 at basis site 7 evaluated for the species s_0 (i.e., the species residing at site 0 of the cluster)"

2) Energies, including ECI, are always reported in eV. If you are finding large ECI, it may indicate that your training data are nearly linear dependent in the correlation space of your fit (especially if large ECI in pairs of positive/negative values of comparable magnitude). You might consider calculating more training data to broaden the distribution of your data in correlation space. The `novelty` query can help identify configurations that will improve the distribution of your dataset (larger values indicate configurations that more 'novel' relative to the distribution of a particular selection).  

You can also try using a different `casm-learn` estimator. `LassoCV` will tend to find solutions that have smaller ECI (and will also find solutions that are more sparse). 

If neither of these strategies work, there may be some pathology in your training data (e.g., malformed input, very large relaxations or structural changes, etc.). The `basis_deformation` and `lattice_deformation` queries can help you identify configurations that have undergone very large relaxation. They are both measured in Angstr/atom, so reasonable values should be significantly less than 1 Angstr (and usually less than 0.1 Angstr).
