### ISSUE TITLE
Binary coupled cluster expansion reference

### ISSUE THREAD

**Issue by HojeChun** [prisms-center/CASMcode#90]
Dear cod developers,

Thanks for helpling with using the CASM code.

I am currently trying to conduct binary coupled cluster expansion in order to consider multiple adsorption sites. (Ex. FCC, HCP in (111) surface of FCC structure). I did the same procedure as just binary cluster expansion up to setting reference. However for the reference settings I am not certain to impose the references correctly. In casm ref --desc, there is no example for the coupled cluster expansion reference setting. If I did just casm ref --set-auto, it seems weird as if the code is unable to distinguish with respect to the different adsorption sites. In order to draw 2D energy convex hull, I think I need two reference points starting from 0 coverage. 

Please give some comments on this issue.

Thanks

**Comment by bpuchala** [comment]
The references are based on the chemical composition space so that each composition axis corresponds to an independent chemical potential. In the majority of situations this is the correct composition axes for calculating the convex hull and determining ground states.

Setting up a separate references for different sites, but not composition, and calculating a convex hull means you would also be including a potential that applies to an order parameter. Is this really what you want? Remember, potential ordering is not just one more axis but multi-dimensional. We've actually had a paper just recently accepted on the topic of general calculation of order parameters, but that work is not incorporated in the public version of CASM yet.

If you just want to visualize the energies as a function of composition & order you can use the calculated correlations.

**Comment by HojeChun** [comment]
What I meant by seperate references for different sites is that I want one axis to be site A and the other axis to be the site B, and then z axis would be the formation energy. As you can see in the reference below that has a convex hull with one axis of OH and the other axis of H2O. 
http://pubs.acs.org/doi/abs/10.1021/jp2075379

**Comment by bpuchala** [comment]
In your prim.json what are the allowed occupants on site A vs. site B?

**Comment by HojeChun** [comment]
I allowed occupation variables “I” and “Va” to both site A and B.

**Comment by bpuchala** [comment]
Is "I" supposed to represent OH on one site and H2O on the other basis site? In that case, you'd want to use two different variables, say "OH" and "H2O", or just "A" and "B".

**Comment by HojeChun** [comment]
If so, do I have to change back lets say I used “A” and “B” to “I” in VASP calculation??

**Comment by bpuchala** [comment]
Looking at the paper briefly, I'm not sure if CASM can currently support doing what was done in the paper since we don't support molecular occupation. If you can translate the problem into one with sublattices for oxygen and hydrogen, then it might work.

**Comment by HojeChun** [comment]
Thanks! I will try what you've suggested
