### ISSUE TITLE
Config-level settings ignored

### ISSUE THREAD

**Issue by jonaskaufman** [prisms-center/CASMcode#92]
I had some calculations fail to reach electronic convergence in run.final so I tried to change ALGO by creating a config-level settings directory with a different INCAR. I removed run.final and resubmitted, but the vaspwrapper seems to have ignored the new config-level settings.

**Comment by bpuchala** [comment]
Thank you for reporting this. I'll be looking into it.

**Comment by bpuchala** [comment]
I had to refresh my memory, but this is the way input files are setup:

- The configuration/supercell/global settings are read at initial setup and used to setup the ``run.0`` input files. The ``"INCAR"`` from ``"settings"`` is also copied to ``INCAR.base``. If ``"initial"`` is given in the ``"relax.json"`` file giving the location of a different ``"INCAR"``-file, it is used for ``run.0``. If ``"extra_input_files"`` is given, additional files can be copied into the intial run directory.
- After each run, if it is determined that the convergence has not yet been reached, an additional ``"relax"`` run is performed. Each additional ``"relax"`` run is setup using the files from the previous ``"relax"`` run, specifically those files specified by ``"copy"`` (by default ``"KPOINTS"`` and ``"INCAR"``) and ``"move"`` (by default ``"POTCAR"``) in the ``"relax.json"``.  (Other options include ``"compress", "remove", "backup"``). Additionally, ``"CONTCAR"`` is copied to the new ``"POSCAR"`` and finally the ``"INCAR.base"`` is copied to the new ``"INCAR"``.  This means the ``"INCAR.base"`` is typically overwriting the ``"INCAR"`` copied from the last run and the CASM ``"settings"`` files are *not* used.
- After convergence is reached, a final ``"constant"`` run is performed. The input for this is setup by using the files from the last ``"relax"`` run as before, except if ``"final"`` is specified in the ``"relax.json"`` file giving the location of a different ``"INCAR"``-file, it is used instead of the ``"INCAR"`` from the last ``"relax"`` run.  If ``"final"`` is not given, then the last ``"INCAR"`` is used (*not the ``"INCAR.base"``*), with the modifications: ``{"ISIF":2, "ISMEAR":-5, "NSW":0, "IBRION":-1}`` and ``" final"`` is appended to ``"SYSTEM"``.

This is perhaps excessively complicated, and definitely needs better documentation, but achieves the following:
- You can specify the initial, intermediate, and final INCAR settings separately from the initial settings, along with ``"extra_input_files"``
- You can copy / move / remove / compress / backup results from each run

For your specific case of wishing to modify the INCAR for only the final run, you can remove the ``"run.final"`` directory, create an INCAR the way you like it (remember to also set ``"ISIF", "ISMEAR",  "IBRION"`` appropriately), and specify the absolute path in your configuration-level ``"relax.json"``.

But in the general case of wishing to change INCAR settings, I would recommend just removing all the runs and restart from the beginning.  The configuration-level ``"settings"`` will be then be used to setup the calculations.

**Comment by jonaskaufman** [comment]
Thank you for the explanation. On a related note, there does not seem to be a way to specify a separate `KPOINTS` file on the final run like there is for `INCAR`. This would be a useful feature e.g. for calculating density of states.
