### ISSUE TITLE
How to generate configurations

### ISSUE THREAD

**Issue by Lucien1234** [prisms-center/CASMcode#95]
Hello,
This might be a stupid question but it really confused me. I am using the version of 0.2.1 and use command **casm status -n** to learn to generate structure step by step. All things go fine until the third steps (generate configuration). 
The  NEXT STEP text told that I need to use **casm enum --configs --all** to generate all of the configurations (I have already generate supercells by **casm enum --method ScelEnum --max 4**). I use **casm enum --method SuperConfigEnum -a** command to generate configurations from all of the supercell but the system responsed as such:

terminate called after throwing an instance if ' std::invalid_argument'
 what(): Error in SuperConfigEnum JSON input: 'subconfigs' is required
Aborted (core dumped)

I check the --desc command and found:

Subconfigs: string or JSON array
 Indicate supercells to enumerate all occupational configurations in...By default, all existing supercells are used.
I also check the example and found the file used in example has a name like "SCEL1_1_1_1_0_0_0/0", but in my training_date directory I can only found files like "SCEL1_1_1_1_0_0_0" without the following "/0". 

So I have three questions here:
1. "By default all existing supercells are used", are supercells and subconfigs the same thing?
2. What the role of subconfigs in construct configurations? What will happen if I indicate only one subconfig in JSON array rather than two or more?
3. Where can I find "SCEL1_1_1_1_0_0_0/0"? I can only find "SCEL1_1_1_1_0_0_0" until now.

Thank you!

**Comment by jcthomas** [comment]
It looks like `casm status -n` has not kept up with updates to some of the other commands. `casm enum --method SuperConfigEnum` is a very targeted utility that enumerates superconfigurations by tiling combinations of smaller configurations into supercells, which is why it requires a list of 'subconfigs'.  This requires that some configurations are already present in your project.

If you are enumerating configurations from scratch, you should try `casm enum --method ConfigEnumAllOccupations -a`, which will exhaustively enumerate all symmetrically distinct configurations within your enumerated supercells. If you wish, you may restrict the enumerated configurations using the optional `--filter` argument, which allows you to restrict the enumerated configurations to include only configurations that satisfy a specified query. Another way to restrict enumerated configurations is by enumerating configurations stochastically, using the enumeration method `ConfigEnumRandomOccupations`, which will enumerate a user-specified number of configurations stochastically. These specializations exist in order control the size of your configuration database, which can slow execution if it becomes abnormally large.

Thanks for bringing this issue to our attention. Please let us know if you run into any other issues!

**Comment by Lucien1234** [comment]
Dear Thomas,
Thank you very much! It works.
I will let you know if I meet other issues.

**Comment by skk74** [comment]
On another note, this documentation fix and others like it have been made to the 0.2.X branch of this repository. We tend to push minor fixes between releases to this branch, so it may be helpful to fork that branch for the most up-to-date CASM.
